server:
  port: 3000

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jdbc_api
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop

  kafka:
    bootstrap-servers: localhost:29092

management:
  endpoints:
    web:
      exposure:
        # include: health,prometheus
        include: health
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http:localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0