server:
  port: 3000
# logging:
  # level:
  #   root: INFO
  #   org:
  #     hibernate:
  #       SQL: debug
  #       type:
  #         descriptor:
  #           sql:
  #             BasicBinder: TRACE
  #   tast: warn
  # pattern:
  #   console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{requestId}] - %msg%n"
  # file:
  #   name: myapp.log
  # logback:
  #   rollingpolicy:
  #     max-file-size: 10MB
  #     max-history: 10
  #     total-size-cap: 100MB
  # group:
  #   tast: bcakend, id.co.jamkrindo.backend.controller
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/jdbc_api
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  kafka:
    bootstrap-servers: localhost:29092

management:
  endpoints:
    web:
      exposure:
        # include: health,prometheus
        include: health
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http:localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0